name: Skillify Frontend - CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-to-floresta:
    name: 🚀 Deploy GitOps (ECR + Argo CD)
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    uses: florestaencantada/integration_onprem/.github/workflows/reusable-gitops-deploy.yml@main
    with:
      organization: 'floresta'
      cluster: 'forest-dev'
      app-name: 'skillrush-front'
      ecr-registry: '818928662779.dkr.ecr.us-east-1.amazonaws.com'
      ecr-repository: 'skillify/frontend'
      aws-role-arn: 'arn:aws:iam::818928662779:role/forest-dev-github'
      dockerfile-path: './Dockerfile'
    secrets: inherit
